version: '3'
services: 
  pool-db:
    container_name: pool-db
    image: pool-db
    build: db
    environment:
      - SERVER_PORT=5432
      - TZ=Europe/Moscow
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_PASSWORD=pool
      - MYSQL_USER=pool
      - MYSQL_DATABASE=pool
    volumes:
      - ./data-db:/var/lib/mysql
    restart: unless-stopped
  pool-node:
    container_name: pool-node
    image: pool-node
    build: node
    volumes:
      - ./data-node:/home/fullnode/.dashcore
      - ./logs/notify:/var/log/stratum
    environment:
      - STRATUM_PORT=3573
      - STRATUM_HOST=pool-web
      - STRATUM_COINID=2033
    ports:
      - 11333:11303
      - 11335:11305
    user: fullnode
    command: 
      - /home/fullnode/dashd 
      - "-listen"
      - "-server"
      - "-rest"
      - "-rpcuser=rpc"
      - "-rpcpassword=123"
      - "-rpcallowip=10.0.0.0/8"
      - "-rpcallowip=192.168.0.0/16"
      - "-rpcallowip=127.0.0.0/8"
      - "-rpcallowip=172.0.0.0/8"
      - "-rpcbind=0.0.0.0 -rpcthreads=8"
      - "-alertnotify=/home/fullnode/notify-alert %s"
      - "-blocknotify=/home/fullnode/notify-block %s"
      - "-walletnotify=/home/fullnode/notify-wallet %s"
      - "-instantsendnotify=/home/fullnode/notify-instantsend %s"
    restart: unless-stopped
  pool-web:
    container_name: pool-web
    image: pool-web
    build: web
    ports:
      - 8082:80
      - 3573:3573
      - 3533:3533
    volumes:
      - ~/data-node:/data/bitcore
      - ./logs/nginx:/var/log/nginx
      - ./logs/yiimp:/work/yiimp/log
      - ./logs/fpm:/var/log/fpm
      - ./logs/stratum:/var/stratum/log
      - ./data-backup:/root/backup
    environment:
      - ABE=/abe
      - BLOCKCHAIN=/data
    restart: unless-stopped
  pool-main:
    container_name: pool-main
    image: pool-main
    build: cron
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        curl -s -o - http://pool-web/mainwrapper.php
        sleep 90
      done
      EOF'
    restart: unless-stopped
  pool-blocks:
    container_name: pool-blocks
    image: pool-blocks
    build: cron
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        curl -s -o - http://pool-web/blockswrapper.php
        sleep 20
      done
      EOF'
    restart: unless-stopped
  pool-loop:
    container_name: pool-loop
    image: pool-loop
    build: cron
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        curl -s -o - http://pool-web/loopwrapper.php
        sleep 60
      done
      EOF'
    restart: unless-stopped
#  pool-stratum-x11:
#    container_name: pool-stratum-x11
#    image: pool-stratum-x11
#    build: cron
#    entrypoint: |
#      bash -c 'bash -s <<EOF
#      trap "break;exit" SIGHUP SIGINT SIGTERM
#      while /bin/true; do
#        curl -s -o - http://pool-web/stratumwrapper.php?config=x11
#        sleep 1
#      done
#      EOF'
#    restart: unless-stopped
  pool-stratum-c11:
    container_name: pool-stratum-c11
    image: pool-stratum-c11
    build: cron
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        curl -s -o - http://pool-web/stratumwrapper.php?config=c11
        sleep 1
      done
      EOF'
    restart: unless-stopped

